$axure.loadCurrentPage({
  "url":"home.html",
  "generationDate":new Date(1459356908975.89),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"765f4c3a72444b26b320d967c3d1fe3e",
    "type":"Axure:Page",
    "name":"Home",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"fb5fa1541e81466d845f5223d452a5bd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "size":{
              "width":1350,
              "height":709}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d29c43d9a8c46889c649d9e59796fc3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1350,
                  "height":709}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u0.png"}},
{
          "id":"c9f332e784cf4b6f804840d3023eba2e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "location":{
              "x":335,
              "y":155},
            "size":{
              "width":540,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0099FF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d503f7dd49f493fa6352aba9498c296",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "location":{
                  "x":335,
                  "y":155},
                "size":{
                  "width":540,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u2.png"}},
{
          "id":"f8505776bfdf46d6aaf77786cb1b4ee3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0099FF},
            "location":{
              "x":875,
              "y":155},
            "size":{
              "width":151,
              "height":40},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0550306ac59844e2a1115cebf112494d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF0099FF},
                "location":{
                  "x":875,
                  "y":155},
                "size":{
                  "width":151,
                  "height":40},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u4.png"}},
{
          "id":"473f5146cb194fdb96c64a6e5edaf739",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"46px",
            "fontWeight":"700",
            "location":{
              "x":576,
              "y":68},
            "size":{
              "width":213,
              "height":54}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"df355127b061480ea458dd1a2e66ef5f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"46px",
                "fontWeight":"700",
                "location":{
                  "x":576,
                  "y":68},
                "size":{
                  "width":213,
                  "height":54}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5a55bc6e7af84626bdf3a3e8341c3531",
          "label":"textarea",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "stateStyles":{
              "hint":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "fontWeight":"400",
                "fontStyle":"normal",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1}}},
            "location":{
              "x":344,
              "y":158},
            "size":{
              "width":480,
              "height":36}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onTextChange":{
              "description":"OnTextChange",
              "cases":[{
                  "description":"用例 1<br> (If 文字于 This 等于 &quot;浪潮&quot; 或 文字于 This 等于 &quot;浪潮之&quot; 或 文字于 This 等于 &quot;浪潮之巅&quot;)",
                  "isNewIfGroup":false,
                  "condition":{
                    "exprType":"binaryOp",
                    "op":"||",
                    "leftExpr":{
                      "exprType":"binaryOp",
                      "op":"==",
                      "leftExpr":{
                        "exprType":"fcall",
                        "functionName":"GetWidgetText",
                        "arguments":[{
                            "exprType":"pathLiteral",
                            "isThis":true,
                            "isFocused":false,
                            "isTarget":false}]},
                      "rightExpr":{
                        "exprType":"stringLiteral",
                        "value":"浪潮",
                        "stos":[]}},
                    "rightExpr":{
                      "exprType":"binaryOp",
                      "op":"||",
                      "leftExpr":{
                        "exprType":"binaryOp",
                        "op":"==",
                        "leftExpr":{
                          "exprType":"fcall",
                          "functionName":"GetWidgetText",
                          "arguments":[{
                              "exprType":"pathLiteral",
                              "isThis":true,
                              "isFocused":false,
                              "isTarget":false}]},
                        "rightExpr":{
                          "exprType":"stringLiteral",
                          "value":"浪潮之",
                          "stos":[]}},
                      "rightExpr":{
                        "exprType":"binaryOp",
                        "op":"==",
                        "leftExpr":{
                          "exprType":"fcall",
                          "functionName":"GetWidgetText",
                          "arguments":[{
                              "exprType":"pathLiteral",
                              "isThis":true,
                              "isFocused":false,
                              "isTarget":false}]},
                        "rightExpr":{
                          "exprType":"stringLiteral",
                          "value":"浪潮之巅",
                          "stos":[]}}}},
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 sug to 状态1",
                      "panelsToStates":[{
                          "panelPath":["c18f4567e63c45739ef4721234e384cf"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":2,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]},
{
                      "action":"fadeWidget",
                      "description":"显示 close",
                      "objectsToFades":[{
                          "objectPath":["7c11e86751e44ad1905926989cfba12a"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "placeholderText":"搜索你喜欢或者读过的书名、作者"},
{
          "id":"aea5fc455e6b41c89667df094f693c66",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":103,
              "y":252},
            "size":{
              "width":1147,
              "height":373},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"34291aa02bee445cb5e7fef0ab8e4d28",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":103,
                  "y":252},
                "size":{
                  "width":1147,
                  "height":373},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u9.png"}},
{
          "id":"1efbf7b6374e48bc8f759f3535eed4ea",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1164,
              "y":396},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0e05f861e1ac4dc29852bf3f909bd7e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1164,
                  "y":396},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 booklist to 下一步 wrap",
                      "panelsToStates":[{
                          "panelPath":["2496accd86c24d559e877c3c953ed416"],
                          "stateInfo":{
                            "setStateType":"next",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":true,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u11.png"}},
{
          "id":"68cc5c0541a64da1b96122fa6eafcd6f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":396},
            "size":{
              "width":60,
              "height":60},
            "rotation":"180",
            "textRotation":"180"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8113957691924857bbc9928cdfa6b021",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":140,
                  "y":396},
                "size":{
                  "width":60,
                  "height":60},
                "rotation":"180",
                "textRotation":"180"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 booklist to 上一步 wrap",
                      "panelsToStates":[{
                          "panelPath":["2496accd86c24d559e877c3c953ed416"],
                          "stateInfo":{
                            "setStateType":"previous",
                            "stateNumber":1,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":true,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/home/u11.png"}},
{
          "id":"2496accd86c24d559e877c3c953ed416",
          "label":"booklist",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":244,
              "y":300},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"114cf4cf99584891ac0c0d6573dca3e3",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"c77854837cbf4e4b941c6887c07e6e89",
                  "label":"",
                  "parentDynamicPanel":"2496accd86c24d559e877c3c953ed416",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":184,
                      "height":252}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"dca9b3c8314547cfaf00a9d0afa85aa6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2496accd86c24d559e877c3c953ed416",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":184,
                          "height":252}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u16.jpg"}},
{
                  "id":"bef8c9f4d2664fe89627bf1f77d293a1",
                  "label":"",
                  "parentDynamicPanel":"2496accd86c24d559e877c3c953ed416",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"16px",
                    "location":{
                      "x":48,
                      "y":255},
                    "size":{
                      "width":65,
                      "height":21}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0a74ac08e08c4d43a6d8b75b86502251",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2496accd86c24d559e877c3c953ed416",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'微软雅黑 Regular', '微软雅黑'",
                        "fontSize":"16px",
                        "location":{
                          "x":48,
                          "y":255},
                        "size":{
                          "width":65,
                          "height":21}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"ea91fef1f80c44d084d88e6121bd1cc9",
                  "label":"",
                  "parentDynamicPanel":"2496accd86c24d559e877c3c953ed416",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":235,
                      "y":0},
                    "size":{
                      "width":184,
                      "height":252}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"08da65b5643d4f6da1d04fbf28046f27",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2496accd86c24d559e877c3c953ed416",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":235,
                          "y":0},
                        "size":{
                          "width":184,
                          "height":252}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u20.jpg"}},
{
                  "id":"83866b43cec446b5a099f2c85e1232ff",
                  "label":"",
                  "parentDynamicPanel":"2496accd86c24d559e877c3c953ed416",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"16px",
                    "location":{
                      "x":296,
                      "y":255},
                    "size":{
                      "width":51,
                      "height":21}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8bebce0e42364b50b22090104a22809e",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2496accd86c24d559e877c3c953ed416",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'微软雅黑 Regular', '微软雅黑'",
                        "fontSize":"16px",
                        "location":{
                          "x":296,
                          "y":255},
                        "size":{
                          "width":51,
                          "height":21}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"fdde2088b1e8496b8b7b2471094617bb",
                  "label":"",
                  "parentDynamicPanel":"2496accd86c24d559e877c3c953ed416",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":472,
                      "y":0},
                    "size":{
                      "width":184,
                      "height":252}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"03e8706f61be4b8f96dcf635f317a6df",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2496accd86c24d559e877c3c953ed416",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":472,
                          "y":0},
                        "size":{
                          "width":184,
                          "height":252}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u24.jpg"}},
{
                  "id":"856bd2749fc949dbbbc2b8170fcf6772",
                  "label":"",
                  "parentDynamicPanel":"2496accd86c24d559e877c3c953ed416",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"16px",
                    "location":{
                      "x":520,
                      "y":255},
                    "size":{
                      "width":65,
                      "height":21}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"69632160cded450e838124e3fa265dd1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2496accd86c24d559e877c3c953ed416",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'微软雅黑 Regular', '微软雅黑'",
                        "fontSize":"16px",
                        "location":{
                          "x":520,
                          "y":255},
                        "size":{
                          "width":65,
                          "height":21}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"250b7102c56f4a4384281cb1c243b876",
                  "label":"",
                  "parentDynamicPanel":"2496accd86c24d559e877c3c953ed416",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":707,
                      "y":0},
                    "size":{
                      "width":184,
                      "height":252}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d9bdd603b3834102806b525374a53788",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2496accd86c24d559e877c3c953ed416",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":707,
                          "y":0},
                        "size":{
                          "width":184,
                          "height":252}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u28.jpg"}},
{
                  "id":"8dfd82f7e3304d6f959840973aba49d7",
                  "label":"",
                  "parentDynamicPanel":"2496accd86c24d559e877c3c953ed416",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"16px",
                    "location":{
                      "x":768,
                      "y":255},
                    "size":{
                      "width":49,
                      "height":21}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"77c6be79a036472bb0e415af168ca66a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2496accd86c24d559e877c3c953ed416",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'微软雅黑 Regular', '微软雅黑'",
                        "fontSize":"16px",
                        "location":{
                          "x":768,
                          "y":255},
                        "size":{
                          "width":49,
                          "height":21}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]},
{
              "id":"9b45b10696274059bec18b8732cc255b",
              "label":"状态2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"bc54260fd7d545f6bc439c701084f2a9",
                  "label":"",
                  "parentDynamicPanel":"2496accd86c24d559e877c3c953ed416",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":184,
                      "height":252}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1b7273a0861f49148dc8261283323750",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2496accd86c24d559e877c3c953ed416",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":184,
                          "height":252}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u32.jpg"}},
{
                  "id":"a8dd8732cc69446da3f9a3b5bf10a4e5",
                  "label":"",
                  "parentDynamicPanel":"2496accd86c24d559e877c3c953ed416",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"16px",
                    "location":{
                      "x":48,
                      "y":255},
                    "size":{
                      "width":65,
                      "height":21}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6a9a31c43b0340b6b5bea06c4cb4d2df",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2496accd86c24d559e877c3c953ed416",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'微软雅黑 Regular', '微软雅黑'",
                        "fontSize":"16px",
                        "location":{
                          "x":48,
                          "y":255},
                        "size":{
                          "width":65,
                          "height":21}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"0863ada92a8f446a8e26f25281038a0e",
                  "label":"",
                  "parentDynamicPanel":"2496accd86c24d559e877c3c953ed416",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":235,
                      "y":0},
                    "size":{
                      "width":184,
                      "height":252}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0560e51f3e094173a17079b4f93eb2dd",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2496accd86c24d559e877c3c953ed416",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":235,
                          "y":0},
                        "size":{
                          "width":184,
                          "height":252}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u36.jpg"}},
{
                  "id":"10b1ae219e294c0b96210d47a28910e0",
                  "label":"",
                  "parentDynamicPanel":"2496accd86c24d559e877c3c953ed416",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"16px",
                    "location":{
                      "x":296,
                      "y":255},
                    "size":{
                      "width":49,
                      "height":21}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4531e4809dfd4efda3d9687b1a55afb8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2496accd86c24d559e877c3c953ed416",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'微软雅黑 Regular', '微软雅黑'",
                        "fontSize":"16px",
                        "location":{
                          "x":296,
                          "y":255},
                        "size":{
                          "width":49,
                          "height":21}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"ba33bac68aa84e9c8cb4e113b3eb464a",
                  "label":"",
                  "parentDynamicPanel":"2496accd86c24d559e877c3c953ed416",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":472,
                      "y":0},
                    "size":{
                      "width":184,
                      "height":252}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0550c188492a4c14985283ca16b546e4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2496accd86c24d559e877c3c953ed416",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":472,
                          "y":0},
                        "size":{
                          "width":184,
                          "height":252}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u40.jpg"}},
{
                  "id":"06228cc92c714b79af0ef76b1bcf1556",
                  "label":"",
                  "parentDynamicPanel":"2496accd86c24d559e877c3c953ed416",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"16px",
                    "location":{
                      "x":506,
                      "y":255},
                    "size":{
                      "width":113,
                      "height":21}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"84dff29d66834e5498d95cfee477d977",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2496accd86c24d559e877c3c953ed416",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'微软雅黑 Regular', '微软雅黑'",
                        "fontSize":"16px",
                        "location":{
                          "x":506,
                          "y":255},
                        "size":{
                          "width":113,
                          "height":21}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"edd3a7dfae4647488a75f7632efd566b",
                  "label":"",
                  "parentDynamicPanel":"2496accd86c24d559e877c3c953ed416",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":707,
                      "y":0},
                    "size":{
                      "width":184,
                      "height":252}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4ccb7935cde548b982182f89c0f160f3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2496accd86c24d559e877c3c953ed416",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":707,
                          "y":0},
                        "size":{
                          "width":184,
                          "height":252}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u44.jpg"}},
{
                  "id":"f05e05f48eaa41518fa2acbdf3e9bea1",
                  "label":"",
                  "parentDynamicPanel":"2496accd86c24d559e877c3c953ed416",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "fontSize":"16px",
                    "location":{
                      "x":768,
                      "y":255},
                    "size":{
                      "width":81,
                      "height":21}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5b3d798f7f9b4c8ca9a89932c8eb1ff0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"2496accd86c24d559e877c3c953ed416",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'微软雅黑 Regular', '微软雅黑'",
                        "fontSize":"16px",
                        "location":{
                          "x":768,
                          "y":255},
                        "size":{
                          "width":81,
                          "height":21}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"c18f4567e63c45739ef4721234e384cf",
          "label":"sug",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":335,
              "y":194},
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"e62fbd4c573e4698a2286400389664c2",
              "label":"空白",
              "type":"Axure:PanelDiagram",
              "objects":[]},
{
              "id":"4bd6829b08c4482097ed3745aa042b8d",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"6fd819d977f6472c928fc07c81fbd310",
                  "label":"",
                  "parentDynamicPanel":"c18f4567e63c45739ef4721234e384cf",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":540,
                      "height":326},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC},
                    "outerShadow":{
                      "on":true,
                      "offsetX":5,
                      "offsetY":5,
                      "blurRadius":10,
                      "color":{
                        "r":0,
                        "g":0,
                        "b":0,
                        "a":0.349019607843137}}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"09611db351a9428da6879df6ee511792",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c18f4567e63c45739ef4721234e384cf",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":540,
                          "height":326},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC},
                        "outerShadow":{
                          "on":true,
                          "offsetX":5,
                          "offsetY":5,
                          "blurRadius":10,
                          "color":{
                            "r":0,
                            "g":0,
                            "b":0,
                            "a":0.349019607843137}}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u49.png"}},
{
                  "id":"07efb42873284b849cd9adc20909f948",
                  "label":"bg01",
                  "parentDynamicPanel":"c18f4567e63c45739ef4721234e384cf",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":false,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF0F0F0},
                    "location":{
                      "x":0,
                      "y":1},
                    "size":{
                      "width":540,
                      "height":163},
                    "visible":false,
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b1aa2c3652e7412a8c777b25b13c3742",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c18f4567e63c45739ef4721234e384cf",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":false,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF0F0F0},
                        "location":{
                          "x":0,
                          "y":1},
                        "size":{
                          "width":540,
                          "height":163},
                        "visible":false,
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/bg01_u51.png"}},
{
                  "id":"867384a8d4a84a91a6fb11e7ffc27660",
                  "label":"",
                  "parentDynamicPanel":"c18f4567e63c45739ef4721234e384cf",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":12,
                      "y":9},
                    "size":{
                      "width":104,
                      "height":141}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e0f719b13e574fddb7fbb522c5261147",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c18f4567e63c45739ef4721234e384cf",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":12,
                          "y":9},
                        "size":{
                          "width":104,
                          "height":141}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u53.jpg"}},
{
                  "id":"cc6da5b7639b4a4e9de7405060e59f79",
                  "label":"",
                  "parentDynamicPanel":"c18f4567e63c45739ef4721234e384cf",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":129,
                      "y":83},
                    "size":{
                      "width":366,
                      "height":64}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"bda567ffa65c4908a9ee5b5ba1a23997",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c18f4567e63c45739ef4721234e384cf",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'微软雅黑 Regular', '微软雅黑'",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":129,
                          "y":83},
                        "size":{
                          "width":366,
                          "height":64}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f3a5f4fe7a854bb1a36db393a590ea6f",
                  "label":"",
                  "parentDynamicPanel":"c18f4567e63c45739ef4721234e384cf",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Bold', '微软雅黑'",
                    "fontSize":"16px",
                    "fontWeight":"700",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":129,
                      "y":12},
                    "size":{
                      "width":95,
                      "height":23}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"15aaac497cab4e82b6f07c93b64a229a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c18f4567e63c45739ef4721234e384cf",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'微软雅黑 Bold', '微软雅黑'",
                        "fontSize":"16px",
                        "fontWeight":"700",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":129,
                          "y":12},
                        "size":{
                          "width":95,
                          "height":23}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"ab8be541edcb4848bd3a2a24a0a384de",
                  "label":"",
                  "parentDynamicPanel":"c18f4567e63c45739ef4721234e384cf",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":129,
                      "y":46},
                    "size":{
                      "width":192,
                      "height":28}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6442fdc9636a4c738b8787137ff3b4ed",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c18f4567e63c45739ef4721234e384cf",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'微软雅黑 Regular', '微软雅黑'",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":129,
                          "y":46},
                        "size":{
                          "width":192,
                          "height":28}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"40fa078c34984e85b80aa14abfed7cfa",
                  "label":"bg02",
                  "parentDynamicPanel":"c18f4567e63c45739ef4721234e384cf",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":false,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF0F0F0},
                    "location":{
                      "x":0,
                      "y":163},
                    "size":{
                      "width":540,
                      "height":163},
                    "visible":false,
                    "borderWidth":"-1"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"37509a5b6c364a79a5ec3d4f850a2f1c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c18f4567e63c45739ef4721234e384cf",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":false,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF0F0F0},
                        "location":{
                          "x":0,
                          "y":163},
                        "size":{
                          "width":540,
                          "height":163},
                        "visible":false,
                        "borderWidth":"-1"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onMouseOver":{
                      "description":"OnMouseOver",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 bg02",
                              "objectsToFades":[{
                                  "objectPath":["40fa078c34984e85b80aa14abfed7cfa"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "images":{
                    "normal~":"images/home/bg01_u51.png"}},
{
                  "id":"5f39c5b3fb8043158d085ad90b945b20",
                  "label":"",
                  "parentDynamicPanel":"c18f4567e63c45739ef4721234e384cf",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":12,
                      "y":173},
                    "size":{
                      "width":104,
                      "height":141}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7d74983e849240c08f39a9d5e1e53d99",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c18f4567e63c45739ef4721234e384cf",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":12,
                          "y":173},
                        "size":{
                          "width":104,
                          "height":141}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u63.jpg"}},
{
                  "id":"2b4e440a7ec348b2ba440862b2cc750e",
                  "label":"",
                  "parentDynamicPanel":"c18f4567e63c45739ef4721234e384cf",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":129,
                      "y":247},
                    "size":{
                      "width":366,
                      "height":64}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5fc6c5d99db3490a9f7498778af56247",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c18f4567e63c45739ef4721234e384cf",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'微软雅黑 Regular', '微软雅黑'",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":129,
                          "y":247},
                        "size":{
                          "width":366,
                          "height":64}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"0d898ac4e85c419bb184557f076ae5dd",
                  "label":"",
                  "parentDynamicPanel":"c18f4567e63c45739ef4721234e384cf",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Bold', '微软雅黑'",
                    "fontSize":"16px",
                    "fontWeight":"700",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":129,
                      "y":175},
                    "size":{
                      "width":95,
                      "height":23}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ed64ee84c8ef477ca182f047ac4d414b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c18f4567e63c45739ef4721234e384cf",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'微软雅黑 Bold', '微软雅黑'",
                        "fontSize":"16px",
                        "fontWeight":"700",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":129,
                          "y":175},
                        "size":{
                          "width":95,
                          "height":23}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"b1e184628b614412802a53d71aefddb5",
                  "label":"",
                  "parentDynamicPanel":"c18f4567e63c45739ef4721234e384cf",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Regular', '微软雅黑'",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":129,
                      "y":209},
                    "size":{
                      "width":222,
                      "height":28}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"459ba1371e9c4823917624dfb3f7d10d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c18f4567e63c45739ef4721234e384cf",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'微软雅黑 Regular', '微软雅黑'",
                        "verticalAlignment":"middle",
                        "location":{
                          "x":129,
                          "y":209},
                        "size":{
                          "width":222,
                          "height":28}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"be324be10b2d4d06b5ef99feb4ccf7db",
                  "label":"hot01",
                  "parentDynamicPanel":"c18f4567e63c45739ef4721234e384cf",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":540,
                      "height":163}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 新窗口/标签页 打开 result",
                              "target":{
                                "targetType":"page",
                                "url":"result.html",
                                "includeVariables":true},
                              "linkType":"new"}]}]},
                    "onMouseOver":{
                      "description":"OnMouseOver",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 bg01",
                              "objectsToFades":[{
                                  "objectPath":["07efb42873284b849cd9adc20909f948"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]}]}]},
                    "onMouseOut":{
                      "description":"OnMouseOut",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 bg01",
                              "objectsToFades":[{
                                  "objectPath":["07efb42873284b849cd9adc20909f948"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true},
{
                  "id":"a2a9710e14464f759276f7e79fef224b",
                  "label":"hot02",
                  "parentDynamicPanel":"c18f4567e63c45739ef4721234e384cf",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":163},
                    "size":{
                      "width":540,
                      "height":163}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onMouseOver":{
                      "description":"OnMouseOver",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"显示 bg02",
                              "objectsToFades":[{
                                  "objectPath":["40fa078c34984e85b80aa14abfed7cfa"],
                                  "fadeInfo":{
                                    "fadeType":"show",
                                    "options":{
                                      "showType":"none"}}}]}]}]},
                    "onMouseOut":{
                      "description":"OnMouseOut",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 bg02",
                              "objectsToFades":[{
                                  "objectPath":["40fa078c34984e85b80aa14abfed7cfa"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}}}]}]},
{
          "id":"7c11e86751e44ad1905926989cfba12a",
          "label":"close",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":839,
              "y":163.5},
            "size":{
              "width":26,
              "height":23},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"708403670dd5435ea5345ef051e2ee4a",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"3bcc8387efea4439a88a3e2d331e186e",
                  "label":"",
                  "parentDynamicPanel":"7c11e86751e44ad1905926989cfba12a",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":26,
                      "height":23}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"32097a1f711248e3b9a15179687a1969",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7c11e86751e44ad1905926989cfba12a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":26,
                          "height":23}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/home/u74.png"}},
{
                  "id":"95fd733c529045eda3e9b99d9934e669",
                  "label":"",
                  "parentDynamicPanel":"7c11e86751e44ad1905926989cfba12a",
                  "type":"imageMapRegion",
                  "styleType":"imageMapRegion",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":26,
                      "height":23}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onMouseOver":{
                      "description":"OnMouseOver",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 close to 状态2",
                              "panelsToStates":[{
                                  "panelPath":["7c11e86751e44ad1905926989cfba12a"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}}}]},
{
              "id":"4d5eca7b755946ccb718a3edda8b8737",
              "label":"状态2",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"da7920350b5646f2815e76852363e3a6",
                  "label":"",
                  "parentDynamicPanel":"7c11e86751e44ad1905926989cfba12a",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":2,
                      "y":1},
                    "size":{
                      "width":20,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b18cd570ca5f428e9b6193252e4bc71c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7c11e86751e44ad1905926989cfba12a",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":2,
                          "y":1},
                        "size":{
                          "width":20,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"setPanelState",
                              "description":"设置 sug to 空白",
                              "panelsToStates":[{
                                  "panelPath":["c18f4567e63c45739ef4721234e384cf"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]},
{
                              "action":"fadeWidget",
                              "description":"隐藏 close",
                              "objectsToFades":[{
                                  "objectPath":["7c11e86751e44ad1905926989cfba12a"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/home/u77.png"}}]}]}]}},
  "masters":{
},
  "objectPaths":{
    "fb5fa1541e81466d845f5223d452a5bd":{
      "scriptId":"u0"},
    "8d29c43d9a8c46889c649d9e59796fc3":{
      "scriptId":"u1"},
    "c9f332e784cf4b6f804840d3023eba2e":{
      "scriptId":"u2"},
    "5d503f7dd49f493fa6352aba9498c296":{
      "scriptId":"u3"},
    "f8505776bfdf46d6aaf77786cb1b4ee3":{
      "scriptId":"u4"},
    "0550306ac59844e2a1115cebf112494d":{
      "scriptId":"u5"},
    "473f5146cb194fdb96c64a6e5edaf739":{
      "scriptId":"u6"},
    "df355127b061480ea458dd1a2e66ef5f":{
      "scriptId":"u7"},
    "5a55bc6e7af84626bdf3a3e8341c3531":{
      "scriptId":"u8"},
    "aea5fc455e6b41c89667df094f693c66":{
      "scriptId":"u9"},
    "34291aa02bee445cb5e7fef0ab8e4d28":{
      "scriptId":"u10"},
    "1efbf7b6374e48bc8f759f3535eed4ea":{
      "scriptId":"u11"},
    "0e05f861e1ac4dc29852bf3f909bd7e5":{
      "scriptId":"u12"},
    "68cc5c0541a64da1b96122fa6eafcd6f":{
      "scriptId":"u13"},
    "8113957691924857bbc9928cdfa6b021":{
      "scriptId":"u14"},
    "2496accd86c24d559e877c3c953ed416":{
      "scriptId":"u15"},
    "c77854837cbf4e4b941c6887c07e6e89":{
      "scriptId":"u16"},
    "dca9b3c8314547cfaf00a9d0afa85aa6":{
      "scriptId":"u17"},
    "bef8c9f4d2664fe89627bf1f77d293a1":{
      "scriptId":"u18"},
    "0a74ac08e08c4d43a6d8b75b86502251":{
      "scriptId":"u19"},
    "ea91fef1f80c44d084d88e6121bd1cc9":{
      "scriptId":"u20"},
    "08da65b5643d4f6da1d04fbf28046f27":{
      "scriptId":"u21"},
    "83866b43cec446b5a099f2c85e1232ff":{
      "scriptId":"u22"},
    "8bebce0e42364b50b22090104a22809e":{
      "scriptId":"u23"},
    "fdde2088b1e8496b8b7b2471094617bb":{
      "scriptId":"u24"},
    "03e8706f61be4b8f96dcf635f317a6df":{
      "scriptId":"u25"},
    "856bd2749fc949dbbbc2b8170fcf6772":{
      "scriptId":"u26"},
    "69632160cded450e838124e3fa265dd1":{
      "scriptId":"u27"},
    "250b7102c56f4a4384281cb1c243b876":{
      "scriptId":"u28"},
    "d9bdd603b3834102806b525374a53788":{
      "scriptId":"u29"},
    "8dfd82f7e3304d6f959840973aba49d7":{
      "scriptId":"u30"},
    "77c6be79a036472bb0e415af168ca66a":{
      "scriptId":"u31"},
    "bc54260fd7d545f6bc439c701084f2a9":{
      "scriptId":"u32"},
    "1b7273a0861f49148dc8261283323750":{
      "scriptId":"u33"},
    "a8dd8732cc69446da3f9a3b5bf10a4e5":{
      "scriptId":"u34"},
    "6a9a31c43b0340b6b5bea06c4cb4d2df":{
      "scriptId":"u35"},
    "0863ada92a8f446a8e26f25281038a0e":{
      "scriptId":"u36"},
    "0560e51f3e094173a17079b4f93eb2dd":{
      "scriptId":"u37"},
    "10b1ae219e294c0b96210d47a28910e0":{
      "scriptId":"u38"},
    "4531e4809dfd4efda3d9687b1a55afb8":{
      "scriptId":"u39"},
    "ba33bac68aa84e9c8cb4e113b3eb464a":{
      "scriptId":"u40"},
    "0550c188492a4c14985283ca16b546e4":{
      "scriptId":"u41"},
    "06228cc92c714b79af0ef76b1bcf1556":{
      "scriptId":"u42"},
    "84dff29d66834e5498d95cfee477d977":{
      "scriptId":"u43"},
    "edd3a7dfae4647488a75f7632efd566b":{
      "scriptId":"u44"},
    "4ccb7935cde548b982182f89c0f160f3":{
      "scriptId":"u45"},
    "f05e05f48eaa41518fa2acbdf3e9bea1":{
      "scriptId":"u46"},
    "5b3d798f7f9b4c8ca9a89932c8eb1ff0":{
      "scriptId":"u47"},
    "c18f4567e63c45739ef4721234e384cf":{
      "scriptId":"u48"},
    "6fd819d977f6472c928fc07c81fbd310":{
      "scriptId":"u49"},
    "09611db351a9428da6879df6ee511792":{
      "scriptId":"u50"},
    "07efb42873284b849cd9adc20909f948":{
      "scriptId":"u51"},
    "b1aa2c3652e7412a8c777b25b13c3742":{
      "scriptId":"u52"},
    "867384a8d4a84a91a6fb11e7ffc27660":{
      "scriptId":"u53"},
    "e0f719b13e574fddb7fbb522c5261147":{
      "scriptId":"u54"},
    "cc6da5b7639b4a4e9de7405060e59f79":{
      "scriptId":"u55"},
    "bda567ffa65c4908a9ee5b5ba1a23997":{
      "scriptId":"u56"},
    "f3a5f4fe7a854bb1a36db393a590ea6f":{
      "scriptId":"u57"},
    "15aaac497cab4e82b6f07c93b64a229a":{
      "scriptId":"u58"},
    "ab8be541edcb4848bd3a2a24a0a384de":{
      "scriptId":"u59"},
    "6442fdc9636a4c738b8787137ff3b4ed":{
      "scriptId":"u60"},
    "40fa078c34984e85b80aa14abfed7cfa":{
      "scriptId":"u61"},
    "37509a5b6c364a79a5ec3d4f850a2f1c":{
      "scriptId":"u62"},
    "5f39c5b3fb8043158d085ad90b945b20":{
      "scriptId":"u63"},
    "7d74983e849240c08f39a9d5e1e53d99":{
      "scriptId":"u64"},
    "2b4e440a7ec348b2ba440862b2cc750e":{
      "scriptId":"u65"},
    "5fc6c5d99db3490a9f7498778af56247":{
      "scriptId":"u66"},
    "0d898ac4e85c419bb184557f076ae5dd":{
      "scriptId":"u67"},
    "ed64ee84c8ef477ca182f047ac4d414b":{
      "scriptId":"u68"},
    "b1e184628b614412802a53d71aefddb5":{
      "scriptId":"u69"},
    "459ba1371e9c4823917624dfb3f7d10d":{
      "scriptId":"u70"},
    "be324be10b2d4d06b5ef99feb4ccf7db":{
      "scriptId":"u71"},
    "a2a9710e14464f759276f7e79fef224b":{
      "scriptId":"u72"},
    "7c11e86751e44ad1905926989cfba12a":{
      "scriptId":"u73"},
    "3bcc8387efea4439a88a3e2d331e186e":{
      "scriptId":"u74"},
    "32097a1f711248e3b9a15179687a1969":{
      "scriptId":"u75"},
    "95fd733c529045eda3e9b99d9934e669":{
      "scriptId":"u76"},
    "da7920350b5646f2815e76852363e3a6":{
      "scriptId":"u77"},
    "b18cd570ca5f428e9b6193252e4bc71c":{
      "scriptId":"u78"}}});